---
title: "R Notebook"
---

# Instruktioner

För att aktivera koden, tag bort #-symbolerna framför kodraderna du vill aktivera (**inte** ###-tecknen framför kommentarerna). Klicka sedan på den gröna pilen längst upp till höger i kodstycket för att köra koden.

# Union

```{r}


### Fyll i filnamnet mellan citattecknen för att importera filen

#data1 <- read.csv("FILNAMN 1.csv", header=TRUE)
#data2 <- read.csv("FILNAMN 2.csv", header=TRUE)


### Slå ihop datan

#fullmerge <- merge(data1,data2,all=TRUE)


### Exportera datan till csv

#write.csv(fullmerge,"FILNAMN OUTPUT.csv",row.names=FALSE)


```

# Snitt

```{r}


### Fyll i filnamnet mellan citattecknen för att importera filen

#data1 <- read.csv("FILNAMN 1.csv", header=TRUE)
#data2 <- read.csv("FILNAMN 2.csv", header=TRUE)


### Slå ihop datan

#intersect <- merge(data1,data2,all.y=FALSE)


### Exportera datan till csv

#write.csv(intersect,"FILNAMN OUTPUT.csv",row.names=FALSE)


```

# Komplement

```{r}


### Fyll i filnamnet mellan citattecknen för att importera filen

#data1 <- read.csv("FILNAMN 1.csv", header=TRUE)
#data2 <- read.csv("FILNAMN 2.csv", header=TRUE)


### Matcha datan 
### OBS, fyll i namnet på kolumnerna du vill matcha efter $-tecknen

#comp <- data2[!data2$Namn %in% data1$Namn,]
#rownames(comp) <- NULL


### Exportera datan till csv

#write.csv(comp,"FILNAMN OUTPUT.csv",row.names=FALSE)


```

